index:
    path: /
    controller: App\Controller\ProductsController::index

products:
    path: /products/{page}/{per_page}
    controller: App\Controller\ProductsController::products
    requirements:
        page: '\d+'
        per_page: '\d+'
    defaults:
        page: 1
        per_page: 10